<?php

/**
 * BaseClasificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codigo
 * @property string $nombre
 * @property Doctrine_Collection $SubClasificacion
 * @property Doctrine_Collection $Producto
 * 
 * @method string              getCodigo()           Returns the current record's "codigo" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method Doctrine_Collection getSubClasificacion() Returns the current record's "SubClasificacion" collection
 * @method Doctrine_Collection getProducto()         Returns the current record's "Producto" collection
 * @method Clasificacion       setCodigo()           Sets the current record's "codigo" value
 * @method Clasificacion       setNombre()           Sets the current record's "nombre" value
 * @method Clasificacion       setSubClasificacion() Sets the current record's "SubClasificacion" collection
 * @method Clasificacion       setProducto()         Sets the current record's "Producto" collection
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClasificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clasificacion');
        $this->hasColumn('codigo', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('SubClasificacion', array(
             'local' => 'id',
             'foreign' => 'clasificacion_id'));

        $this->hasMany('Producto', array(
             'local' => 'id',
             'foreign' => 'clasificacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}