<?php

/**
 * BaseItem
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $factura_compra_id
 * @property integer $factura_venta_id
 * @property integer $producto_id
 * @property string $detalle
 * @property integer $precio_unitario
 * @property integer $cantidad
 * @property Producto $Producto
 * @property FacturaCompra $FacturaCompra
 * @property FacturaVenta $FacturaVenta
 * 
 * @method integer       getFacturaCompraId()   Returns the current record's "factura_compra_id" value
 * @method integer       getFacturaVentaId()    Returns the current record's "factura_venta_id" value
 * @method integer       getProductoId()        Returns the current record's "producto_id" value
 * @method string        getDetalle()           Returns the current record's "detalle" value
 * @method integer       getPrecioUnitario()    Returns the current record's "precio_unitario" value
 * @method integer       getCantidad()          Returns the current record's "cantidad" value
 * @method Producto      getProducto()          Returns the current record's "Producto" value
 * @method FacturaCompra getFacturaCompra()     Returns the current record's "FacturaCompra" value
 * @method FacturaVenta  getFacturaVenta()      Returns the current record's "FacturaVenta" value
 * @method Item          setFacturaCompraId()   Sets the current record's "factura_compra_id" value
 * @method Item          setFacturaVentaId()    Sets the current record's "factura_venta_id" value
 * @method Item          setProductoId()        Sets the current record's "producto_id" value
 * @method Item          setDetalle()           Sets the current record's "detalle" value
 * @method Item          setPrecioUnitario()    Sets the current record's "precio_unitario" value
 * @method Item          setCantidad()          Sets the current record's "cantidad" value
 * @method Item          setProducto()          Sets the current record's "Producto" value
 * @method Item          setFacturaCompra()     Sets the current record's "FacturaCompra" value
 * @method Item          setFacturaVenta()      Sets the current record's "FacturaVenta" value
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItem extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item');
        $this->hasColumn('factura_compra_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('factura_venta_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('producto_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('detalle', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('precio_unitario', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('cantidad', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Producto', array(
             'local' => 'producto_id',
             'foreign' => 'id'));

        $this->hasOne('FacturaCompra', array(
             'local' => 'factura_compra_id',
             'foreign' => 'id'));

        $this->hasOne('FacturaVenta', array(
             'local' => 'factura_venta_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}