<?php

/**
 * BaseDepartamento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $abreviacion
 * @property string $codigo
 * @property Doctrine_Collection $Provincias
 * @property Doctrine_Collection $Personas
 * 
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getAbreviacion() Returns the current record's "abreviacion" value
 * @method string              getCodigo()      Returns the current record's "codigo" value
 * @method Doctrine_Collection getProvincias()  Returns the current record's "Provincias" collection
 * @method Doctrine_Collection getPersonas()    Returns the current record's "Personas" collection
 * @method Departamento        setNombre()      Sets the current record's "nombre" value
 * @method Departamento        setAbreviacion() Sets the current record's "abreviacion" value
 * @method Departamento        setCodigo()      Sets the current record's "codigo" value
 * @method Departamento        setProvincias()  Sets the current record's "Provincias" collection
 * @method Departamento        setPersonas()    Sets the current record's "Personas" collection
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDepartamento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('departamento');
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('abreviacion', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('codigo', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Provincia as Provincias', array(
             'local' => 'id',
             'foreign' => 'seguros_departamento_id'));

        $this->hasMany('Persona as Personas', array(
             'local' => 'id',
             'foreign' => 'expedido_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}