<?php

/**
 * BaseNotaVenta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $cliente
 * @property Doctrine_Collection $Producto
 * 
 * @method string              getCliente()  Returns the current record's "cliente" value
 * @method Doctrine_Collection getProducto() Returns the current record's "Producto" collection
 * @method NotaVenta           setCliente()  Sets the current record's "cliente" value
 * @method NotaVenta           setProducto() Sets the current record's "Producto" collection
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNotaVenta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nota_venta');
        $this->hasColumn('cliente', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Producto', array(
             'local' => 'id',
             'foreign' => 'nota_venta_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}