<?php

/**
 * BaseDomicilioLegal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $empresa_id
 * @property integer $localidad_id
 * @property string $direccion
 * @property string $numero
 * @property string $edificio
 * @property string $telefono
 * @property string $fax
 * @property Doctrine_Collection $Empresa
 * @property Localidad $Localidad
 * 
 * @method integer             getEmpresaId()    Returns the current record's "empresa_id" value
 * @method integer             getLocalidadId()  Returns the current record's "localidad_id" value
 * @method string              getDireccion()    Returns the current record's "direccion" value
 * @method string              getNumero()       Returns the current record's "numero" value
 * @method string              getEdificio()     Returns the current record's "edificio" value
 * @method string              getTelefono()     Returns the current record's "telefono" value
 * @method string              getFax()          Returns the current record's "fax" value
 * @method Doctrine_Collection getEmpresa()      Returns the current record's "Empresa" collection
 * @method Localidad           getLocalidad()    Returns the current record's "Localidad" value
 * @method DomicilioLegal      setEmpresaId()    Sets the current record's "empresa_id" value
 * @method DomicilioLegal      setLocalidadId()  Sets the current record's "localidad_id" value
 * @method DomicilioLegal      setDireccion()    Sets the current record's "direccion" value
 * @method DomicilioLegal      setNumero()       Sets the current record's "numero" value
 * @method DomicilioLegal      setEdificio()     Sets the current record's "edificio" value
 * @method DomicilioLegal      setTelefono()     Sets the current record's "telefono" value
 * @method DomicilioLegal      setFax()          Sets the current record's "fax" value
 * @method DomicilioLegal      setEmpresa()      Sets the current record's "Empresa" collection
 * @method DomicilioLegal      setLocalidad()    Sets the current record's "Localidad" value
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDomicilioLegal extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('domicilio_legal');
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('localidad_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('direccion', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('numero', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('edificio', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('telefono', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
        $this->hasColumn('fax', 'string', 15, array(
             'type' => 'string',
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $this->hasOne('Localidad', array(
             'local' => 'localidad_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}