<?php

/**
 * BaseLocalidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seguros_provincia_id
 * @property string $nombre
 * @property string $seccion
 * @property Provincia $Provincia
 * @property Doctrine_Collection $Distritos
 * @property Doctrine_Collection $Personas
 * @property Doctrine_Collection $DomicilioLegal
 * 
 * @method integer             getSegurosProvinciaId()   Returns the current record's "seguros_provincia_id" value
 * @method string              getNombre()               Returns the current record's "nombre" value
 * @method string              getSeccion()              Returns the current record's "seccion" value
 * @method Provincia           getProvincia()            Returns the current record's "Provincia" value
 * @method Doctrine_Collection getDistritos()            Returns the current record's "Distritos" collection
 * @method Doctrine_Collection getPersonas()             Returns the current record's "Personas" collection
 * @method Doctrine_Collection getDomicilioLegal()       Returns the current record's "DomicilioLegal" collection
 * @method Localidad           setSegurosProvinciaId()   Sets the current record's "seguros_provincia_id" value
 * @method Localidad           setNombre()               Sets the current record's "nombre" value
 * @method Localidad           setSeccion()              Sets the current record's "seccion" value
 * @method Localidad           setProvincia()            Sets the current record's "Provincia" value
 * @method Localidad           setDistritos()            Sets the current record's "Distritos" collection
 * @method Localidad           setPersonas()             Sets the current record's "Personas" collection
 * @method Localidad           setDomicilioLegal()       Sets the current record's "DomicilioLegal" collection
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocalidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('localidad');
        $this->hasColumn('seguros_provincia_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('seccion', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Provincia', array(
             'local' => 'seguros_provincia_id',
             'foreign' => 'id'));

        $this->hasMany('Distrito as Distritos', array(
             'local' => 'id',
             'foreign' => 'localidad_id'));

        $this->hasMany('Persona as Personas', array(
             'local' => 'id',
             'foreign' => 'lugar_nacimiento_id'));

        $this->hasMany('DomicilioLegal', array(
             'local' => 'id',
             'foreign' => 'localidad_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}