<?php

/**
 * BaseProducto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $modelo
 * @property string $marca
 * @property string $detalle
 * @property integer $costo
 * @property integer $clasificacion_id
 * @property boolean $stock
 * 
 * @method string   getNombre()           Returns the current record's "nombre" value
 * @method string   getModelo()           Returns the current record's "modelo" value
 * @method string   getMarca()            Returns the current record's "marca" value
 * @method string   getDetalle()          Returns the current record's "detalle" value
 * @method integer  getCosto()            Returns the current record's "costo" value
 * @method integer  getClasificacionId()  Returns the current record's "clasificacion_id" value
 * @method boolean  getStock()            Returns the current record's "stock" value
 * @method Producto setNombre()           Sets the current record's "nombre" value
 * @method Producto setModelo()           Sets the current record's "modelo" value
 * @method Producto setMarca()            Sets the current record's "marca" value
 * @method Producto setDetalle()          Sets the current record's "detalle" value
 * @method Producto setCosto()            Sets the current record's "costo" value
 * @method Producto setClasificacionId()  Sets the current record's "clasificacion_id" value
 * @method Producto setStock()            Sets the current record's "stock" value
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProducto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('producto');
        $this->hasColumn('nombre', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('modelo', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('marca', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('detalle', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('costo', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('clasificacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('stock', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}