<?php

/**
 * BaseDistrito
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $localidad_id
 * @property string $nombre
 * @property Localidad $Localidad
 * 
 * @method integer   getLocalidadId()  Returns the current record's "localidad_id" value
 * @method string    getNombre()       Returns the current record's "nombre" value
 * @method Localidad getLocalidad()    Returns the current record's "Localidad" value
 * @method Distrito  setLocalidadId()  Sets the current record's "localidad_id" value
 * @method Distrito  setNombre()       Sets the current record's "nombre" value
 * @method Distrito  setLocalidad()    Sets the current record's "Localidad" value
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDistrito extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('distrito');
        $this->hasColumn('localidad_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Localidad', array(
             'local' => 'localidad_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}