<?php

/**
 * BasePais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codigo
 * @property string $nombre
 * @property string $continente
 * @property string $region
 * @property integer $poblacion
 * @property string $jefe_estado
 * @property string $capital
 * @property Persona $Persona
 * 
 * @method string  getCodigo()      Returns the current record's "codigo" value
 * @method string  getNombre()      Returns the current record's "nombre" value
 * @method string  getContinente()  Returns the current record's "continente" value
 * @method string  getRegion()      Returns the current record's "region" value
 * @method integer getPoblacion()   Returns the current record's "poblacion" value
 * @method string  getJefeEstado()  Returns the current record's "jefe_estado" value
 * @method string  getCapital()     Returns the current record's "capital" value
 * @method Persona getPersona()     Returns the current record's "Persona" value
 * @method Pais    setCodigo()      Sets the current record's "codigo" value
 * @method Pais    setNombre()      Sets the current record's "nombre" value
 * @method Pais    setContinente()  Sets the current record's "continente" value
 * @method Pais    setRegion()      Sets the current record's "region" value
 * @method Pais    setPoblacion()   Sets the current record's "poblacion" value
 * @method Pais    setJefeEstado()  Sets the current record's "jefe_estado" value
 * @method Pais    setCapital()     Sets the current record's "capital" value
 * @method Pais    setPersona()     Sets the current record's "Persona" value
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pais');
        $this->hasColumn('codigo', 'string', 3, array(
             'type' => 'string',
             'length' => 3,
             ));
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('continente', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('region', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('poblacion', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('jefe_estado', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('capital', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Persona', array(
             'local' => 'id',
             'foreign' => 'pais_origen_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}