<?php

/**
 * BaseProvincia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $seguros_departamento_id
 * @property string $nombre
 * @property Departamento $Departamento
 * @property Doctrine_Collection $Localidades
 * 
 * @method integer             getSegurosDepartamentoId()   Returns the current record's "seguros_departamento_id" value
 * @method string              getNombre()                  Returns the current record's "nombre" value
 * @method Departamento        getDepartamento()            Returns the current record's "Departamento" value
 * @method Doctrine_Collection getLocalidades()             Returns the current record's "Localidades" collection
 * @method Provincia           setSegurosDepartamentoId()   Sets the current record's "seguros_departamento_id" value
 * @method Provincia           setNombre()                  Sets the current record's "nombre" value
 * @method Provincia           setDepartamento()            Sets the current record's "Departamento" value
 * @method Provincia           setLocalidades()             Sets the current record's "Localidades" collection
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProvincia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('provincia');
        $this->hasColumn('seguros_departamento_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Departamento', array(
             'local' => 'seguros_departamento_id',
             'foreign' => 'id'));

        $this->hasMany('Localidad as Localidades', array(
             'local' => 'id',
             'foreign' => 'seguros_provincia_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}