<?php

/**
 * BaseEmpresa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $razon_social
 * @property string $sigla
 * @property integer $tipo_constitucion_empresa_id
 * @property date $fecha_constitucion
 * @property date $fecha_inicio_actividades
 * @property string $numero_doc_constitucion
 * @property date $fecha_doc_constitucion
 * @property integer $actividad_economica_id
 * @property string $nit
 * @property enum $tipo_dependencia
 * @property string $web
 * @property boolean $is_active
 * @property integer $user_id
 * @property TipoConstitucionEmpresa $TipoConstitucionEmpresa
 * @property ActividadEconomica $ActividadEconomica
 * @property DomicilioLegal $DomicilioLegal
 * @property RepresentanteLegal $RepresentanteLegal
 * @property Doctrine_Collection $Empresas
 * @property Doctrine_Collection $Sucursales
 * @property sfGuardUser $sfGuardUser
 * @property Doctrine_Collection $OficinaPrincipalSucursal
 * @property Doctrine_Collection $FacturaVenta
 * 
 * @method string                  getRazonSocial()                  Returns the current record's "razon_social" value
 * @method string                  getSigla()                        Returns the current record's "sigla" value
 * @method integer                 getTipoConstitucionEmpresaId()    Returns the current record's "tipo_constitucion_empresa_id" value
 * @method date                    getFechaConstitucion()            Returns the current record's "fecha_constitucion" value
 * @method date                    getFechaInicioActividades()       Returns the current record's "fecha_inicio_actividades" value
 * @method string                  getNumeroDocConstitucion()        Returns the current record's "numero_doc_constitucion" value
 * @method date                    getFechaDocConstitucion()         Returns the current record's "fecha_doc_constitucion" value
 * @method integer                 getActividadEconomicaId()         Returns the current record's "actividad_economica_id" value
 * @method string                  getNit()                          Returns the current record's "nit" value
 * @method enum                    getTipoDependencia()              Returns the current record's "tipo_dependencia" value
 * @method string                  getWeb()                          Returns the current record's "web" value
 * @method boolean                 getIsActive()                     Returns the current record's "is_active" value
 * @method integer                 getUserId()                       Returns the current record's "user_id" value
 * @method TipoConstitucionEmpresa getTipoConstitucionEmpresa()      Returns the current record's "TipoConstitucionEmpresa" value
 * @method ActividadEconomica      getActividadEconomica()           Returns the current record's "ActividadEconomica" value
 * @method DomicilioLegal          getDomicilioLegal()               Returns the current record's "DomicilioLegal" value
 * @method RepresentanteLegal      getRepresentanteLegal()           Returns the current record's "RepresentanteLegal" value
 * @method Doctrine_Collection     getEmpresas()                     Returns the current record's "Empresas" collection
 * @method Doctrine_Collection     getSucursales()                   Returns the current record's "Sucursales" collection
 * @method sfGuardUser             getSfGuardUser()                  Returns the current record's "sfGuardUser" value
 * @method Doctrine_Collection     getOficinaPrincipalSucursal()     Returns the current record's "OficinaPrincipalSucursal" collection
 * @method Doctrine_Collection     getFacturaVenta()                 Returns the current record's "FacturaVenta" collection
 * @method Empresa                 setRazonSocial()                  Sets the current record's "razon_social" value
 * @method Empresa                 setSigla()                        Sets the current record's "sigla" value
 * @method Empresa                 setTipoConstitucionEmpresaId()    Sets the current record's "tipo_constitucion_empresa_id" value
 * @method Empresa                 setFechaConstitucion()            Sets the current record's "fecha_constitucion" value
 * @method Empresa                 setFechaInicioActividades()       Sets the current record's "fecha_inicio_actividades" value
 * @method Empresa                 setNumeroDocConstitucion()        Sets the current record's "numero_doc_constitucion" value
 * @method Empresa                 setFechaDocConstitucion()         Sets the current record's "fecha_doc_constitucion" value
 * @method Empresa                 setActividadEconomicaId()         Sets the current record's "actividad_economica_id" value
 * @method Empresa                 setNit()                          Sets the current record's "nit" value
 * @method Empresa                 setTipoDependencia()              Sets the current record's "tipo_dependencia" value
 * @method Empresa                 setWeb()                          Sets the current record's "web" value
 * @method Empresa                 setIsActive()                     Sets the current record's "is_active" value
 * @method Empresa                 setUserId()                       Sets the current record's "user_id" value
 * @method Empresa                 setTipoConstitucionEmpresa()      Sets the current record's "TipoConstitucionEmpresa" value
 * @method Empresa                 setActividadEconomica()           Sets the current record's "ActividadEconomica" value
 * @method Empresa                 setDomicilioLegal()               Sets the current record's "DomicilioLegal" value
 * @method Empresa                 setRepresentanteLegal()           Sets the current record's "RepresentanteLegal" value
 * @method Empresa                 setEmpresas()                     Sets the current record's "Empresas" collection
 * @method Empresa                 setSucursales()                   Sets the current record's "Sucursales" collection
 * @method Empresa                 setSfGuardUser()                  Sets the current record's "sfGuardUser" value
 * @method Empresa                 setOficinaPrincipalSucursal()     Sets the current record's "OficinaPrincipalSucursal" collection
 * @method Empresa                 setFacturaVenta()                 Sets the current record's "FacturaVenta" collection
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEmpresa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empresa');
        $this->hasColumn('razon_social', 'string', 500, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 500,
             ));
        $this->hasColumn('sigla', 'string', 250, array(
             'type' => 'string',
             'length' => 250,
             ));
        $this->hasColumn('tipo_constitucion_empresa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('fecha_constitucion', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('fecha_inicio_actividades', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('numero_doc_constitucion', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('fecha_doc_constitucion', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('actividad_economica_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nit', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('tipo_dependencia', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'OFICINA PRINCIPAL',
              1 => 'SUCURSAL',
             ),
             'notnull' => true,
             ));
        $this->hasColumn('web', 'string', 150, array(
             'type' => 'string',
             'length' => 150,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoConstitucionEmpresa', array(
             'local' => 'tipo_constitucion_empresa_id',
             'foreign' => 'id'));

        $this->hasOne('ActividadEconomica', array(
             'local' => 'actividad_economica_id',
             'foreign' => 'id'));

        $this->hasOne('DomicilioLegal', array(
             'local' => 'id',
             'foreign' => 'empresa_id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('RepresentanteLegal', array(
             'local' => 'id',
             'foreign' => 'empresa_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Empresa as Empresas', array(
             'refClass' => 'OficinaPrincipalSucursal',
             'local' => 'sucursal_id',
             'foreign' => 'oficina_principal_id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Empresa as Sucursales', array(
             'refClass' => 'OficinaPrincipalSucursal',
             'local' => 'oficina_principal_id',
             'foreign' => 'sucursal_id'));

        $this->hasOne('sfGuardUser', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasMany('OficinaPrincipalSucursal', array(
             'local' => 'id',
             'foreign' => 'oficina_principal_id'));

        $this->hasMany('FacturaVenta', array(
             'local' => 'empresa_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}