<?php

/**
 * BaseFacturaCompra
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $razon_social
 * @property string $nit
 * @property integer $numero
 * @property integer $numero_autorizacion
 * @property string $codigo_control
 * @property date $fecha
 * @property integer $importe_total
 * @property Doctrine_Collection $Item
 * 
 * @method string              getRazonSocial()         Returns the current record's "razon_social" value
 * @method string              getNit()                 Returns the current record's "nit" value
 * @method integer             getNumero()              Returns the current record's "numero" value
 * @method integer             getNumeroAutorizacion()  Returns the current record's "numero_autorizacion" value
 * @method string              getCodigoControl()       Returns the current record's "codigo_control" value
 * @method date                getFecha()               Returns the current record's "fecha" value
 * @method integer             getImporteTotal()        Returns the current record's "importe_total" value
 * @method Doctrine_Collection getItem()                Returns the current record's "Item" collection
 * @method FacturaCompra       setRazonSocial()         Sets the current record's "razon_social" value
 * @method FacturaCompra       setNit()                 Sets the current record's "nit" value
 * @method FacturaCompra       setNumero()              Sets the current record's "numero" value
 * @method FacturaCompra       setNumeroAutorizacion()  Sets the current record's "numero_autorizacion" value
 * @method FacturaCompra       setCodigoControl()       Sets the current record's "codigo_control" value
 * @method FacturaCompra       setFecha()               Sets the current record's "fecha" value
 * @method FacturaCompra       setImporteTotal()        Sets the current record's "importe_total" value
 * @method FacturaCompra       setItem()                Sets the current record's "Item" collection
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFacturaCompra extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('factura_compra');
        $this->hasColumn('razon_social', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('nit', 'string', 12, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 12,
             ));
        $this->hasColumn('numero', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('numero_autorizacion', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('codigo_control', 'string', 250, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 250,
             ));
        $this->hasColumn('fecha', 'date', null, array(
             'type' => 'date',
             'notnull' => true,
             ));
        $this->hasColumn('importe_total', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Item', array(
             'local' => 'id',
             'foreign' => 'factura_compra_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}