<?php

/**
 * BaseSubClasificacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $clasificacion_id
 * @property string $codigo
 * @property string $nombre
 * @property Clasificacion $Clasificacion
 * @property Doctrine_Collection $Producto
 * 
 * @method integer             getClasificacionId()  Returns the current record's "clasificacion_id" value
 * @method string              getCodigo()           Returns the current record's "codigo" value
 * @method string              getNombre()           Returns the current record's "nombre" value
 * @method Clasificacion       getClasificacion()    Returns the current record's "Clasificacion" value
 * @method Doctrine_Collection getProducto()         Returns the current record's "Producto" collection
 * @method SubClasificacion    setClasificacionId()  Sets the current record's "clasificacion_id" value
 * @method SubClasificacion    setCodigo()           Sets the current record's "codigo" value
 * @method SubClasificacion    setNombre()           Sets the current record's "nombre" value
 * @method SubClasificacion    setClasificacion()    Sets the current record's "Clasificacion" value
 * @method SubClasificacion    setProducto()         Sets the current record's "Producto" collection
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubClasificacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sub_clasificacion');
        $this->hasColumn('clasificacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('codigo', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('nombre', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Clasificacion', array(
             'local' => 'clasificacion_id',
             'foreign' => 'id'));

        $this->hasMany('Producto', array(
             'local' => 'id',
             'foreign' => 'sub_clasificacion_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}