<?php

/**
 * BaseTipoConstitucionEmpresa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property string $sigla
 * @property string $codigo
 * @property boolean $is_active
 * @property Doctrine_Collection $Empresas
 * 
 * @method string                  getNombre()    Returns the current record's "nombre" value
 * @method string                  getSigla()     Returns the current record's "sigla" value
 * @method string                  getCodigo()    Returns the current record's "codigo" value
 * @method boolean                 getIsActive()  Returns the current record's "is_active" value
 * @method Doctrine_Collection     getEmpresas()  Returns the current record's "Empresas" collection
 * @method TipoConstitucionEmpresa setNombre()    Sets the current record's "nombre" value
 * @method TipoConstitucionEmpresa setSigla()     Sets the current record's "sigla" value
 * @method TipoConstitucionEmpresa setCodigo()    Sets the current record's "codigo" value
 * @method TipoConstitucionEmpresa setIsActive()  Sets the current record's "is_active" value
 * @method TipoConstitucionEmpresa setEmpresas()  Sets the current record's "Empresas" collection
 * 
 * @package    takeoff
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoConstitucionEmpresa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_constitucion_empresa');
        $this->hasColumn('nombre', 'string', 150, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 150,
             ));
        $this->hasColumn('sigla', 'string', 5, array(
             'type' => 'string',
             'length' => 5,
             ));
        $this->hasColumn('codigo', 'string', 2, array(
             'type' => 'string',
             'length' => 2,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Empresa as Empresas', array(
             'local' => 'id',
             'foreign' => 'tipo_constitucion_empresa_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $signable0 = new Doctrine_Template_Signable(array(
             ));
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}