<?php

/**
 * ActividadEconomicaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActividadEconomicaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ActividadEconomicaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ActividadEconomica');
    }
}