<?php

/**
 * ClasificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClasificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClasificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Clasificacion');
    }
}