<?php

/**
 * DepartamentoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DepartamentoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DepartamentoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Departamento');
    }
}