<?php

/**
 * DistritoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DistritoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DistritoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Distrito');
    }
}