<?php

/**
 * DomicilioLegalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DomicilioLegalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DomicilioLegalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DomicilioLegal');
    }
}