<?php

/**
 * FacturaCompraTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacturaCompraTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacturaCompraTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FacturaCompra');
    }
}