<?php

/**
 * FacturaVentaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FacturaVentaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FacturaVentaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('FacturaVenta');
    }
}