<?php

/**
 * NotaVentaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NotaVentaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NotaVentaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NotaVenta');
    }
}