<?php

/**
 * OficinaPrincipalSucursalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class OficinaPrincipalSucursalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object OficinaPrincipalSucursalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('OficinaPrincipalSucursal');
    }
}