<?php

/**
 * SubClasificacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SubClasificacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SubClasificacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SubClasificacion');
    }
}