<?php

/**
 * TipoConstitucionEmpresaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoConstitucionEmpresaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoConstitucionEmpresaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoConstitucionEmpresa');
    }
}